[SHC]
Title=Sharecoin
Address=
Ip=127.0.0.1
Port=8332
Username=
Password=
AddressPrefix=63
ScriptPrefix=18
SecretPrefix=214
COIN=100000000
MinimumAmount=0
TxVersion=2
DustAmount=0
CreateTxMethod=BTC
GetNewKeySupported=true
ImportWithNoScanSupported=true
MinTxFee=1000
BlockTime=120
FeePerByte=1
Confirmations=0
